# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Rust (Cargo)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "cargo"
    labels:
      - "dependencies"
      - "ci"
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "gha"
    labels:
      - "dependencies"
      - "ci"
    groups:
      gha-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "ci"
    groups:
      docker-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Custom cross-rs target images
  - package-ecosystem: "docker"
    directory: "/docker/cross"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "docker-cross"
    labels:
      - "dependencies"
      - "ci"
